apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: opentelemetry-collector
    repoURL:  https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.116.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/PierreStephaneVoltaire/Kubernetes-playground-observability/refs/heads/master/monitoring/values/otel-collector-values.yaml

