apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otlp
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.116.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/PierreStephaneVoltaire/Kubernetes-playground-observability/refs/heads/master/monitoring/values/otlp-values.yaml
    chart: open-telemetry/opentelemetry-collector
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
