grafana:
  adminUser: "admin"
  adminPassword: "grafana-password"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          basicAuth: false
          access: proxy
          isDefault: true
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local:9090
          access: proxy