loki:
  storage:
    type: "s3"
    s3:
      region: ca-central-1
    bucketNames:
      chunks: playground-loki-logs-bucket
      ruler: playground-loki-logs-bucket
      admin: playground-loki-logs-bucket
serviceAccount:
  create: false  
  name: loki-service-account  

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"