image:
  repository: otel/opentelemetry-collector
  tag: latest
mode: daemonset

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    batch: {}
  exporters:
    otlphttp:
      endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi