prometheus:
  annotations: {}
  server:
    persistentVolume:
      enabled: true
      storageClass: gp3
      size: 50Gi
  prometheusSpec:
    serviceMonitorSelector: {}
    logLevel: debug
grafana:
  enabled: false
