prometheus:
  annotations: {}
  server:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistentVolume:
      enabled: true
      storageClass: gp3
      size: 20Gi
  prometheusSpec:
    serviceMonitorSelector: {}
    logLevel: debug
grafana:
  adminUser: "admin"
  adminPassword: "grafana-password"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki-gateway.meta.svc.cluster.local:80
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
  persistence:
    type: pvc
    enabled: true
    storageClassName: "gp3"
  service:
    type: LoadBalancer