prometheus:
  annotations: {}
  server:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistentVolume:
      enabled: true
      storageClass: gp3
      size: 50Gi
  prometheusSpec:
    serviceMonitorSelector: {}
    logLevel: debug
grafana:
  adminUser: "admin"
  adminPassword: "grafana-password"
  persistence:
    type: pvc
    enabled: true
    storageClassName: "gp3"
  service:
    type: LoadBalancer